BREAKABLE_OBJS = {
    "Bowl",
    "ShowerGlass",
    "Statue",
    "Television",
    "Vase",
    "Bottle",
    "WineBottle",
    "ShowerDoor",
    "Laptop",
    "Cup",
    "Egg",
    "CellPhone",
    "Mirror",
    "Plate",
    "Mug",
    "Window",
}

CLEANABLE_OBJS = {"Bowl", "Pan", "Pot", "Cloth", "Cup", "Plate", "Mirror", "Mug", "Bed"}

MOVABLE_OBJS = {
    "Toaster",
    "GarbageBag",
    "Chair",
    "Microwave",
    "Safe",
    "ShelvingUnit",
    "DogBed",
    "DiningTable",
    "FloorLamp",
    "Sofa",
    "VacuumCleaner",
    "CoffeeMachine",
    "RoomDecor",
    "ArmChair",
    "TVStand",
    "Television",
    "CoffeeTable",
    "Desk",
    "Stool",
    "Ottoman",
    "LaundryHamper",
    "DeskLamp",
    "SideTable",
    "HousePlant",
    "Desktop",
    "Footstool",
    "GarbageCan",
    "Dresser",
}
OPENABLE_OBJS = {
    "Drawer",
    "Box",
    "ShowerDoor",
    "Microwave",
    "Safe",
    "ShowerCurtain",
    "Laptop",
    "Toilet",
    "Book",
    "Cabinet",
    "Fridge",
    "Kettle",
}
GRASPABLE_OBJS = {
    "Pen",
    "Statue",
    "TableTopDecor",
    "CreditCard",
    "Bread",
    "TeddyBear",
    "DishSponge",
    "LettuceSliced*",
    "PaperTowelRoll",
    "CellPhone",
    "Plate",
    "WateringCan",
    "Ladle",
    "Potato",
    "TomatoSliced*",
    "KeyChain",
    "Kettle",
    "Vase",
    "Plunger",
    "CD",
    "WineBottle",
    "SaltShaker",
    "Spatula",
    "Pan",
    "Pot",
    "Towel",
    "Apple",
    "Cloth",
    "SoapBottle",
    "Knife",
    "Cup",
    "Spoon",
    "Pencil",
    "Mug",
    "Newspaper",
    "Candle",
    "AluminumFoil",
    "Box",
    "Pillow",
    "BasketBall",
    "Watch",
    "Laptop",
    "TissueBox",
    "Egg",
    "Book",
    "ButterKnife",
    "PepperShaker",
    "TennisRacket",
    "RemoteControl",
    "SoapBar",
    "ToiletPaper",
    "Bowl",
    "Dumbbell",
    "Boots",
    "Bottle",
    "BaseballBat",
    "AlarmClock",
    "EggCracked*",
    "Fork",
    "PotatoSliced*",
    "HandTowel",
    "BreadSliced*",
    "ScrubBrush",
    "SprayBottle",
    "AppleSliced*",
    "Tomato",
    "Lettuce",
}

POWER_OBJS = {
    "Toaster",
    "Faucet",
    "Candle",
    "FloorLamp",
    "Television",
    "Microwave",
    "CoffeeMachine",
    "ShowerHead",
    "StoveKnob",
    "Laptop",
    "LightSwitch",
    "StoveBurner",
    "CellPhone",
    "DeskLamp",
}
USEDUP_OBJS = {"PaperTowelRoll", "TissueBox", "SoapBottle", "ToiletPaper"}

RECEP_OBJS = {
    "Toaster",
    "Microwave",
    "Safe",
    "ToiletPaperHanger",
    "Plate",
    "DiningTable",
    "Shelf",
    "Sofa",
    "Drawer",
    "CoffeeMachine",
    "Pan",
    "Pot",
    "Cup",
    "Cabinet",
    "Mug",
    "ArmChair",
    "TowelHolder",
    "TVStand",
    "CoffeeTable",
    "Box",
    "Desk",
    "StoveBurner",
    "Ottoman",
    "Fridge",
    "HandTowelHolder",
    "LaundryHamper",
    "Bathtub",
    "Bowl",
    "BathtubBasin",
    "SideTable",
    "SinkBasin",
    "GarbageCan",
    "Sink",
    "Toilet",
    "Dresser",
    "CounterTop",
    "Bed",
}
OBJ_RECEP = {
    ("Ladle", "Drawer"),
    ("CD", "Shelf"),
    ("ButterKnife", "Desk"),
    ("Book", "Shelf"),
    ("DishSponge", "CoffeeTable"),
    ("Apple", "Sink"),
    ("BaseballBat", "SideTable"),
    ("Bowl", "Microwave"),
    ("Potato", "SideTable"),
    ("CellPhone", "CounterTop"),
    ("Newspaper", "CounterTop"),
    ("Watch", "TVStand"),
    ("AlarmClock", "Shelf"),
    ("AppleSliced*", "TVStand"),
    ("Candle", "Drawer"),
    ("Kettle", "StoveBurner"),
    ("Lettuce", "DiningTable"),
    ("Pillow", "Bed"),
    ("ButterKnife", "Sink"),
    ("Pencil", "CounterTop"),
    ("LettuceSliced*", "Plate"),
    ("CellPhone", "SideTable"),
    ("SoapBar", "SinkBasin"),
    ("Bread", "CoffeeTable"),
    ("Newspaper", "SideTable"),
    ("Apple", "Fridge"),
    ("DishSponge", "Pot"),
    ("HandTowel", "HandTowelHolder"),
    ("Candle", "Bathtub"),
    ("SoapBar", "Bathtub"),
    ("DishSponge", "Cabinet"),
    ("Laptop", "ArmChair"),
    ("Cup", "Cabinet"),
    ("BaseballBat", "Bed"),
    ("Bottle", "Sink"),
    ("Apple", "Dresser"),
    ("Pan", "TVStand"),
    ("Fork", "Sink"),
    ("Spoon", "Pan"),
    ("AppleSliced*", "Plate"),
    ("DishSponge", "BathtubBasin"),
    ("EggCracked*", "Sink"),
    ("Cloth", "Dresser"),
    ("BreadSliced*", "DiningTable"),
    ("Cloth", "Cart"),
    ("AppleSliced*", "GarbageCan"),
    ("Spoon", "Mug"),
    ("AppleSliced*", "Microwave"),
    ("Safe", ""),
    ("SideTable", ""),
    ("CD", "Safe"),
    ("CellPhone", "Bed"),
    ("Painting", ""),
    ("Newspaper", "Bed"),
    ("Bowl", "DiningTable"),
    ("Bottle", "Fridge"),
    ("CD", "Cabinet"),
    ("SoapBottle", "Drawer"),
    ("Vase", "Dresser"),
    ("Book", "Cabinet"),
    ("Vase", "Cart"),
    ("TeddyBear", "TVStand"),
    ("KeyChain", "Ottoman"),
    ("BaseballBat", "Desk"),
    ("DogBed", ""),
    ("Fork", "TVStand"),
    ("CreditCard", "CounterTop"),
    ("ToiletPaper", "Shelf"),
    ("EggCracked*", "Fridge"),
    ("EggCracked*", "TVStand"),
    ("Pen", "Mug"),
    ("Bottle", "Dresser"),
    ("Spoon", "CoffeeTable"),
    ("Tomato", "CoffeeTable"),
    ("Statue", "SideTable"),
    ("Toaster", ""),
    ("Box", "CoffeeTable"),
    ("CellPhone", "Desk"),
    ("Potato", "Sink"),
    ("RemoteControl", "Ottoman"),
    ("SaltShaker", "TVStand"),
    ("Apple", "Bowl"),
    ("Newspaper", "Desk"),
    ("KeyChain", "Shelf"),
    ("ArmChair", ""),
    ("WateringCan", "TVStand"),
    ("TissueBox", "GarbageCan"),
    ("Laptop", "DiningTable"),
    ("Pen", "CoffeeTable"),
    ("CreditCard", "Drawer"),
    ("Knife", "SideTable"),
    ("SoapBar", "TVStand"),
    ("Spoon", "Pot"),
    ("Tomato", "Pot"),
    ("Potato", "Fridge"),
    ("BaseballBat", "TVStand"),
    ("SprayBottle", "SideTable"),
    ("WineBottle", "Fridge"),
    ("RemoteControl", "Shelf"),
    ("Newspaper", "Toilet"),
    ("DishSponge", "Drawer"),
    ("WineBottle", "Dresser"),
    ("Cloth", "LaundryHamper"),
    ("CellPhone", "TVStand"),
    ("Knife", "SinkBasin"),
    ("Newspaper", "TVStand"),
    ("TissueBox", "Box"),
    ("Box", "SideTable"),
    ("TomatoSliced*", "GarbageCan"),
    ("ToiletPaper", "Cabinet"),
    ("TeddyBear", "Sofa"),
    ("Pot", "SideTable"),
    ("SoapBar", "GarbageCan"),
    ("Pencil", "TVStand"),
    ("CD", "Drawer"),
    ("Statue", "Desk"),
    ("Book", "Drawer"),
    ("TissueBox", "DiningTable"),
    ("BreadSliced*", "CounterTop"),
    ("PotatoSliced*", "SideTable"),
    ("LettuceSliced*", "CoffeeTable"),
    ("Plate", "DiningTable"),
    ("Apple", "Pan"),
    ("Bowl", "CounterTop"),
    ("ShowerHead", ""),
    ("Spatula", "DiningTable"),
    ("Cloth", "Shelf"),
    ("Potato", "Bowl"),
    ("Drawer", ""),
    ("DishSponge", "Cart"),
    ("Bread", "Fridge"),
    ("ButterKnife", "Pan"),
    ("Candle", "Box"),
    ("Bowl", "SideTable"),
    ("PepperShaker", "Shelf"),
    ("Ladle", "DiningTable"),
    ("Vase", "Shelf"),
    ("ButterKnife", "Mug"),
    ("Cloth", "DiningTable"),
    ("Knife", "Sink"),
    ("LettuceSliced*", "Pot"),
    ("Pencil", "GarbageCan"),
    ("Watch", "CoffeeTable"),
    ("Statue", "TVStand"),
    ("CreditCard", "TVStand"),
    ("Floor", ""),
    ("SoapBottle", "GarbageCan"),
    ("TomatoSliced*", "DiningTable"),
    ("Pillow", "Ottoman"),
    ("Spoon", "Drawer"),
    ("ToiletPaper", "ToiletPaperHanger"),
    ("Vase", "DiningTable"),
    ("Apple", "CoffeeTable"),
    ("CellPhone", "Sofa"),
    ("Newspaper", "Sofa"),
    ("Laptop", "CounterTop"),
    ("BasketBall", "ArmChair"),
    ("ToiletPaperHanger", ""),
    ("Fork", "Pan"),
    ("Bowl", "SinkBasin"),
    ("EggCracked*", "Pan"),
    ("ButterKnife", "CoffeeTable"),
    ("Egg", "Plate"),
    ("Fork", "Mug"),
    ("Pan", "CoffeeTable"),
    ("Pen", "Drawer"),
    ("Egg", "GarbageCan"),
    ("Egg", "Microwave"),
    ("ToiletPaper", "Drawer"),
    ("Pot", "Sink"),
    ("Apple", "Pot"),
    ("CreditCard", "ArmChair"),
    ("StoveKnob", ""),
    ("Kettle", "CounterTop"),
    ("SprayBottle", "Dresser"),
    ("AppleSliced*", "SideTable"),
    ("CoffeeMachine", ""),
    ("Bottle", "CoffeeTable"),
    ("BreadSliced*", "Desk"),
    ("ButterKnife", "Pot"),
    ("Cloth", "Cabinet"),
    ("PotatoSliced*", "Sink"),
    ("Fork", "CoffeeTable"),
    ("HousePlant", ""),
    ("Newspaper", "Ottoman"),
    ("EggCracked*", "CoffeeTable"),
    ("Vase", "Safe"),
    ("KeyChain", "Drawer"),
    ("Pot", "Fridge"),
    ("Bowl", "Desk"),
    ("Kettle", "SideTable"),
    ("PepperShaker", "Cabinet"),
    ("Potato", "Pan"),
    ("DishSponge", "GarbageCan"),
    ("Vase", "Cabinet"),
    ("SoapBottle", "DiningTable"),
    ("WineBottle", "Shelf"),
    ("Laptop", "Bed"),
    ("Box", "Dresser"),
    ("AppleSliced*", "SinkBasin"),
    ("TissueBox", "CounterTop"),
    ("SaltShaker", "CoffeeTable"),
    ("PotatoSliced*", "Fridge"),
    ("Pan", "SideTable"),
    ("Fork", "Pot"),
    ("RemoteControl", "Drawer"),
    ("Bottle", "Cabinet"),
    ("Plate", "CounterTop"),
    ("CreditCard", "Box"),
    ("BasketBall", "DiningTable"),
    ("EggCracked*", "Pot"),
    ("CD", "ArmChair"),
    ("Kettle", "SinkBasin"),
    ("Book", "ArmChair"),
    ("Lettuce", "Plate"),
    ("Spatula", "CounterTop"),
    ("Egg", "DiningTable"),
    ("BreadSliced*", "TVStand"),
    ("CD", "GarbageCan"),
    ("Lettuce", "GarbageCan"),
    ("BaseballBat", "CoffeeTable"),
    ("Boots", ""),
    ("Laptop", "Desk"),
    ("DishSponge", "Box"),
    ("TeddyBear", "SideTable"),
    ("Bowl", "TVStand"),
    ("Ladle", "CounterTop"),
    ("Cloth", "CounterTop"),
    ("LettuceSliced*", "Sink"),
    ("TennisRacket", "CounterTop"),
    ("DishSponge", "Shelf"),
    ("AppleSliced*", "Desk"),
    ("TomatoSliced*", "CounterTop"),
    ("Tomato", "Bowl"),
    ("CellPhone", "CoffeeTable"),
    ("Vase", "CounterTop"),
    ("Newspaper", "CoffeeTable"),
    ("Potato", "Pot"),
    ("DishSponge", "DiningTable"),
    ("Plate", "SinkBasin"),
    ("TennisRacket", "SideTable"),
    ("BreadSliced*", "Plate"),
    ("Cup", "DiningTable"),
    ("CD", "Box"),
    ("LettuceSliced*", "Fridge"),
    ("AppleSliced*", "Sink"),
    ("TomatoSliced*", "SideTable"),
    ("Book", "Box"),
    ("WateringCan", "SideTable"),
    ("WineBottle", "Cabinet"),
    ("Spatula", "SinkBasin"),
    ("TeddyBear", "Bed"),
    ("BreadSliced*", "Microwave"),
    ("Mug", "CounterTop"),
    ("Cloth", "Drawer"),
    ("Candle", "SideTable"),
    ("PotatoSliced*", "Bowl"),
    ("SoapBar", "SideTable"),
    ("Laptop", "TVStand"),
    ("ButterKnife", "Drawer"),
    ("AlarmClock", "Box"),
    ("Ladle", "SinkBasin"),
    ("PepperShaker", "Drawer"),
    ("CD", "DiningTable"),
    ("Mug", "SideTable"),
    ("AppleSliced*", "Fridge"),
    ("Book", "DiningTable"),
    ("TissueBox", "Desk"),
    ("TomatoSliced*", "SinkBasin"),
    ("Cloth", "Bathtub"),
    ("TennisRacket", "Bed"),
    ("Pan", "Sink"),
    ("Plate", "Desk"),
    ("Knife", "Pan"),
    ("Box", "Ottoman"),
    ("TeddyBear", "Desk"),
    ("AlarmClock", "DiningTable"),
    ("Watch", "Dresser"),
    ("ToiletPaper", "GarbageCan"),
    ("Kettle", "TVStand"),
    ("Knife", "Mug"),
    ("SoapBottle", "CounterTop"),
    ("Mug", "SinkBasin"),
    ("Statue", "CoffeeTable"),
    ("Pencil", "SideTable"),
    ("TissueBox", "Toilet"),
    ("Pan", "Fridge"),
    ("KeyChain", "ArmChair"),
    ("TennisRacket", "Desk"),
    ("SoapBottle", "SideTable"),
    ("BasketBall", "CounterTop"),
    ("LettuceSliced*", "Bowl"),
    ("Box", "Shelf"),
    ("Shelf", ""),
    ("WateringCan", "Desk"),
    ("Knife", "CoffeeTable"),
    ("Egg", "CounterTop"),
    ("TissueBox", "TVStand"),
    ("Pen", "Box"),
    ("Spoon", "DiningTable"),
    ("Candle", "Desk"),
    ("Ottoman", ""),
    ("Plate", "TVStand"),
    ("RemoteControl", "ArmChair"),
    ("SprayBottle", "CoffeeTable"),
    ("BasketBall", "SideTable"),
    ("Tomato", "DiningTable"),
    ("Pen", "Shelf"),
    ("Laptop", "Sofa"),
    ("Spatula", "TVStand"),
    ("Egg", "SideTable"),
    ("PotatoSliced*", "Pan"),
    ("Bed", ""),
    ("CoffeeTable", ""),
    ("Knife", "Pot"),
    ("Pen", "DiningTable"),
    ("SoapBar", "Sink"),
    ("SoapBottle", "Bathtub"),
    ("TeddyBear", "Dresser"),
    ("ToiletPaper", "DiningTable"),
    ("KeyChain", "Box"),
    ("CreditCard", "SideTable"),
    ("DishSponge", "CounterTop"),
    ("Ladle", "TVStand"),
    ("Candle", "Toilet"),
    ("SoapBar", "Toilet"),
    ("TennisRacket", "TVStand"),
    ("Cup", "CounterTop"),
    ("DiningTable", ""),
    ("Pot", "CoffeeTable"),
    ("SprayBottle", "Cabinet"),
    ("TomatoSliced*", "TVStand"),
    ("RoomDecor", ""),
    ("BasketBall", "Bed"),
    ("Egg", "SinkBasin"),
    ("ButterKnife", "Bowl"),
    ("Plunger", "Cart"),
    ("Vase", "TVStand"),
    ("Pencil", "Desk"),
    ("Candle", "TVStand"),
    ("Plate", "Microwave"),
    ("RemoteControl", "Box"),
    ("Spatula", "Plate"),
    ("Cup", "SideTable"),
    ("KeyChain", "DiningTable"),
    ("PotatoSliced*", "CoffeeTable"),
    ("SoapBottle", "Desk"),
    ("WateringCan", "Dresser"),
    ("CD", "CounterTop"),
    ("Mug", "TVStand"),
    ("Book", "CounterTop"),
    ("Box", "Cabinet"),
    ("Lettuce", "CounterTop"),
    ("Ladle", "Plate"),
    ("Cloth", "ArmChair"),
    ("BreadSliced*", "CoffeeTable"),
    ("BreadSliced*", "Toaster"),
    ("Cloth", "GarbageCan"),
    ("LettuceSliced*", "Pan"),
    ("BasketBall", "Desk"),
    ("RemoteControl", "DiningTable"),
    ("DishSponge", "SinkBasin"),
    ("AlarmClock", "CounterTop"),
    ("Fork", "Bowl"),
    ("TomatoSliced*", "Plate"),
    ("CD", "SideTable"),
    ("Cup", "SinkBasin"),
    ("EggCracked*", "Bowl"),
    ("PotatoSliced*", "Pot"),
    ("Book", "SideTable"),
    ("Bowl", "CoffeeTable"),
    ("Lettuce", "SideTable"),
    ("SoapBottle", "Toilet"),
    ("DishSponge", "Bathtub"),
    ("CellPhone", "Dresser"),
    ("Newspaper", "Dresser"),
    ("AlarmClock", "SideTable"),
    ("ShowerGlass", ""),
    ("Watch", "Shelf"),
    ("CreditCard", "Desk"),
    ("AppleSliced*", "Pan"),
    ("SoapBottle", "TVStand"),
    ("KeyChain", "Safe"),
    ("Bottle", "GarbageCan"),
    ("Lettuce", "SinkBasin"),
    ("Cloth", "Box"),
    ("Spoon", "CounterTop"),
    ("Book", "Bed"),
    ("Tomato", "CounterTop"),
    ("BasketBall", "TVStand"),
    ("Cup", "Desk"),
    ("BreadSliced*", "SideTable"),
    ("Laptop", "CoffeeTable"),
    ("TeddyBear", "Ottoman"),
    ("Vase", "Box"),
    ("Faucet", ""),
    ("Apple", "DiningTable"),
    ("Egg", "TVStand"),
    ("SprayBottle", "Drawer"),
    ("AppleSliced*", "CoffeeTable"),
    ("Pen", "CounterTop"),
    ("ToiletPaper", "CounterTop"),
    ("ButterKnife", "DiningTable"),
    ("TableTopDecor", ""),
    ("Bottle", "Box"),
    ("CD", "Desk"),
    ("DishSponge", "Toilet"),
    ("PepperShaker", "DiningTable"),
    ("Book", "Desk"),
    ("Kettle", "CoffeeTable"),
    ("Bottle", "Shelf"),
    ("Potato", "GarbageCan"),
    ("Statue", "Dresser"),
    ("WineBottle", "GarbageCan"),
    ("Spoon", "SinkBasin"),
    ("ToiletPaper", "SideTable"),
    ("ShowerDoor", ""),
    ("AppleSliced*", "Pot"),
    ("Statue", "Cart"),
    ("DishSponge", "TVStand"),
    ("AlarmClock", "Desk"),
    ("Watch", "Safe"),
    ("Cup", "TVStand"),
    ("Bottle", "DiningTable"),
    ("KeyChain", "CounterTop"),
    ("Lettuce", "Sink"),
    ("Fork", "DiningTable"),
    ("Laptop", "SideTable"),
    ("EggCracked*", "DiningTable"),
    ("SaltShaker", "Shelf"),
    ("Stool", ""),
    ("TissueBox", "CoffeeTable"),
    ("RemoteControl", "CounterTop"),
    ("Plate", "CoffeeTable"),
    ("SprayBottle", "Cart"),
    ("CD", "TVStand"),
    ("CellPhone", "Ottoman"),
    ("TeddyBear", "CoffeeTable"),
    ("Book", "TVStand"),
    ("ToiletPaper", "Bathtub"),
    ("BasketBall", "Sofa"),
    ("Lettuce", "TVStand"),
    ("Towel", "TowelHolder"),
    ("DishSponge", "Plate"),
    ("Pan", "Cabinet"),
    ("AlarmClock", "TVStand"),
    ("Cup", "Microwave"),
    ("TennisRacket", "CoffeeTable"),
    ("Potato", "DiningTable"),
    ("CreditCard", "Sofa"),
    ("WineBottle", "DiningTable"),
    ("Bowl", "Sink"),
    ("Bread", "Plate"),
    ("Pen", "Desk"),
    ("CellPhone", "Shelf"),
    ("TomatoSliced*", "CoffeeTable"),
    ("BreadSliced*", "GarbageCan"),
    ("WateringCan", "CoffeeTable"),
    ("Newspaper", "Shelf"),
    ("ToiletPaper", "Desk"),
    ("Knife", "Bowl"),
    ("Bread", "GarbageCan"),
    ("Bread", "Microwave"),
    ("Candle", "CoffeeTable"),
    ("BreadSliced*", "Fridge"),
    ("SoapBar", "CoffeeTable"),
    ("TissueBox", "SideTable"),
    ("AluminumFoil", ""),
    ("TowelHolder", ""),
    ("Plate", "SideTable"),
    ("Apple", "CounterTop"),
    ("Plunger", "Cabinet"),
    ("Pot", "StoveBurner"),
    ("HandTowelHolder", ""),
    ("Spoon", "TVStand"),
    ("Bowl", "Fridge"),
    ("Mug", "CoffeeTable"),
    ("Pencil", "Mug"),
    ("SaltShaker", "Cabinet"),
    ("Tomato", "TVStand"),
    ("TomatoSliced*", "Pot"),
    ("Spatula", "SideTable"),
    ("KeyChain", "Desk"),
    ("ButterKnife", "CounterTop"),
    ("ToiletPaper", "Toilet"),
    ("Watch", "Drawer"),
    ("CreditCard", "Ottoman"),
    ("PepperShaker", "CounterTop"),
    ("Bowl", "Dresser"),
    ("Ladle", "SideTable"),
    ("Cloth", "SideTable"),
    ("Pen", "TVStand"),
    ("CD", "Sofa"),
    ("SprayBottle", "GarbageCan"),
    ("Bathtub", ""),
    ("Book", "Sofa"),
    ("ToiletPaper", "TVStand"),
    ("RemoteControl", "Desk"),
    ("Mirror", ""),
    ("Dumbbell", ""),
    ("Pencil", "CoffeeTable"),
    ("Bottle", "CounterTop"),
    ("Vase", "SideTable"),
    ("Spoon", "Plate"),
    ("SoapBar", "BathtubBasin"),
    ("Fork", "CounterTop"),
    ("SoapBottle", "CoffeeTable"),
    ("Apple", "SinkBasin"),
    ("Box", "ArmChair"),
    ("CellPhone", "Safe"),
    ("Tomato", "Plate"),
    ("Statue", "Shelf"),
    ("Chair", ""),
    ("Bread", "DiningTable"),
    ("EggCracked*", "CounterTop"),
    ("Kettle", "Sink"),
    ("Tomato", "GarbageCan"),
    ("Cloth", "SinkBasin"),
    ("Fridge", ""),
    ("Newspaper", "Cabinet"),
    ("KeyChain", "TVStand"),
    ("ButterKnife", "SinkBasin"),
    ("Laptop", "Dresser"),
    ("Statue", "DiningTable"),
    ("TargetCircle", ""),
    ("BasketBall", "CoffeeTable"),
    ("CD", "Ottoman"),
    ("Pen", "GarbageCan"),
    ("Egg", "CoffeeTable"),
    ("AppleSliced*", "Dresser"),
    ("SprayBottle", "Shelf"),
    ("RemoteControl", "TVStand"),
    ("Fork", "Drawer"),
    ("Knife", "DiningTable"),
    ("Bottle", "SinkBasin"),
    ("Apple", "Desk"),
    ("CreditCard", "CoffeeTable"),
    ("Plate", "Sink"),
    ("Potato", "CounterTop"),
    ("SprayBottle", "DiningTable"),
    ("WineBottle", "CounterTop"),
    ("Cloth", "Desk"),
    ("Spatula", "Sink"),
    ("Egg", "Pot"),
    ("SaltShaker", "Drawer"),
    ("Lettuce", "Pan"),
    ("Vase", "Desk"),
    ("Pot", "Shelf"),
    ("WateringCan", "Drawer"),
    ("Cup", "CoffeeTable"),
    ("WineBottle", "SideTable"),
    ("Ladle", "Sink"),
    ("Plate", "Fridge"),
    ("Cloth", "Sink"),
    ("Statue", "Safe"),
    ("Box", "DiningTable"),
    ("SoapBar", "Drawer"),
    ("TissueBox", "Dresser"),
    ("Pot", "DiningTable"),
    ("Cloth", "Toilet"),
    ("TomatoSliced*", "Sink"),
    ("AppleSliced*", "Bowl"),
    ("Bottle", "Desk"),
    ("TissueBox", "Cart"),
    ("Plate", "Dresser"),
    ("Apple", "TVStand"),
    ("KeyChain", "Sofa"),
    ("LettuceSliced*", "GarbageCan"),
    ("Spoon", "Cup"),
    ("Pan", "StoveBurner"),
    ("CD", "CoffeeTable"),
    ("Potato", "SinkBasin"),
    ("Toilet", ""),
    ("Book", "CoffeeTable"),
    ("Cloth", "TVStand"),
    ("Lettuce", "CoffeeTable"),
    ("PotatoSliced*", "DiningTable"),
    ("CellPhone", "Drawer"),
    ("ButterKnife", "TVStand"),
    ("Newspaper", "Drawer"),
    ("TomatoSliced*", "Fridge"),
    ("PepperShaker", "TVStand"),
    ("AlarmClock", "CoffeeTable"),
    ("TVStand", ""),
    ("Bowl", "Shelf"),
    ("RemoteControl", "Sofa"),
    ("DishSponge", "SideTable"),
    ("TennisRacket", "Dresser"),
    ("Pencil", "Drawer"),
    ("Bread", "CounterTop"),
    ("Laptop", "Ottoman"),
    ("Lettuce", "Pot"),
    ("Apple", "Plate"),
    ("Bottle", "TVStand"),
    ("Candle", "Dresser"),
    ("Apple", "GarbageCan"),
    ("Statue", "CounterTop"),
    ("Candle", "Cart"),
    ("Apple", "Microwave"),
    ("SoapBar", "Cart"),
    ("Pot", "Cabinet"),
    ("WineBottle", "Desk"),
    ("Bread", "SideTable"),
    ("ButterKnife", "Plate"),
    ("SoapBottle", "Sink"),
    ("Spatula", "Bowl"),
    ("Watch", "Box"),
    ("Knife", "CounterTop"),
    ("LettuceSliced*", "DiningTable"),
    ("Ladle", "Bowl"),
    ("SprayBottle", "CounterTop"),
    ("Blinds", ""),
    ("Window", ""),
    ("TeddyBear", "ArmChair"),
    ("Egg", "Sink"),
    ("Fork", "Plate"),
    ("TomatoSliced*", "Bowl"),
    ("Cloth", "Sofa"),
    ("ToiletPaper", "CoffeeTable"),
    ("EggCracked*", "Plate"),
    ("Pencil", "Dresser"),
    ("Sofa", ""),
    ("Watch", "DiningTable"),
    ("AppleSliced*", "DiningTable"),
    ("Potato", "TVStand"),
    ("Kettle", "Shelf"),
    ("EggCracked*", "GarbageCan"),
    ("Bowl", "Cabinet"),
    ("WineBottle", "TVStand"),
    ("EggCracked*", "Microwave"),
    ("SoapBottle", "Dresser"),
    ("GarbageBag", ""),
    ("Box", "CounterTop"),
    ("RemoteControl", "Dresser"),
    ("SoapBottle", "Cart"),
    ("Knife", "Drawer"),
    ("Pillow", "ArmChair"),
    ("Microwave", ""),
    ("Pot", "CounterTop"),
    ("Egg", "Fridge"),
    ("Kettle", "DiningTable"),
    ("Spoon", "SideTable"),
    ("KeyChain", "CoffeeTable"),
    ("LightSwitch", ""),
    ("BasketBall", "Dresser"),
    ("DishSponge", "Sink"),
    ("Tomato", "SideTable"),
    ("Bread", "Desk"),
    ("Cup", "Sink"),
    ("PotatoSliced*", "CounterTop"),
    ("TissueBox", "Shelf"),
    ("Pan", "DiningTable"),
    ("Cloth", "Ottoman"),
    ("Potato", "Plate"),
    ("Plate", "Shelf"),
    ("Pen", "SideTable"),
    ("RemoteControl", "CoffeeTable"),
    ("FloorLamp", ""),
    ("Potato", "Microwave"),
    ("CreditCard", "Dresser"),
    ("Poster", ""),
    ("Tomato", "SinkBasin"),
    ("Pillow", "Sofa"),
    ("Spatula", "Pan"),
    ("Cup", "Fridge"),
    ("PaperTowelRoll", ""),
    ("ButterKnife", "Cup"),
    ("CellPhone", "ArmChair"),
    ("TeddyBear", "DiningTable"),
    ("Newspaper", "ArmChair"),
    ("GarbageCan", ""),
    ("Pot", "SinkBasin"),
    ("Footstool", ""),
    ("Ladle", "Pan"),
    ("Newspaper", "GarbageCan"),
    ("Cup", "Dresser"),
    ("SprayBottle", "Desk"),
    ("Kettle", "Cabinet"),
    ("KeyChain", "SideTable"),
    ("Bread", "TVStand"),
    ("WateringCan", "Shelf"),
    ("PotatoSliced*", "SinkBasin"),
    ("SaltShaker", "DiningTable"),
    ("ShelvingUnit", ""),
    ("Egg", "Bowl"),
    ("Lettuce", "Fridge"),
    ("Candle", "Shelf"),
    ("SoapBar", "Shelf"),
    ("TennisRacket", "DiningTable"),
    ("Fork", "Cup"),
    ("SinkBasin", ""),
    ("LettuceSliced*", "CounterTop"),
    ("Spatula", "CoffeeTable"),
    ("WateringCan", "DiningTable"),
    ("RemoteControl", "SideTable"),
    ("Box", "Desk"),
    ("CD", "Dresser"),
    ("Mug", "Shelf"),
    ("Book", "Dresser"),
    ("Candle", "DiningTable"),
    ("SoapBar", "DiningTable"),
    ("SprayBottle", "Toilet"),
    ("VacuumCleaner", ""),
    ("CellPhone", "Box"),
    ("Ladle", "CoffeeTable"),
    ("Cloth", "CoffeeTable"),
    ("TissueBox", "Cabinet"),
    ("BaseballBat", "DiningTable"),
    ("LettuceSliced*", "SideTable"),
    ("Knife", "TVStand"),
    ("Spoon", "Sink"),
    ("TeddyBear", "Safe"),
    ("LaundryHamper", ""),
    ("Plate", "Cabinet"),
    ("Watch", "CounterTop"),
    ("AlarmClock", "Dresser"),
    ("Mug", "DiningTable"),
    ("Tomato", "Sink"),
    ("AppleSliced*", "CounterTop"),
    ("Spatula", "Pot"),
    ("PepperShaker", "CoffeeTable"),
    ("DishSponge", "Bowl"),
    ("SprayBottle", "TVStand"),
    ("Vase", "CoffeeTable"),
    ("Pencil", "Box"),
    ("StoveBurner", ""),
    ("DeskLamp", ""),
    ("CellPhone", "DiningTable"),
    ("Ladle", "Pot"),
    ("Newspaper", "DiningTable"),
    ("Pencil", "Shelf"),
    ("Watch", "SideTable"),
    ("LettuceSliced*", "SinkBasin"),
    ("Cabinet", ""),
    ("Ladle", "Cabinet"),
    ("Tomato", "Fridge"),
    ("SoapBottle", "Shelf"),
    ("Box", "TVStand"),
    ("Pencil", "DiningTable"),
    ("Knife", "Plate"),
    ("Sink", ""),
    ("WateringCan", "Cabinet"),
    ("Pot", "TVStand"),
    ("Pan", "CounterTop"),
    ("Apple", "SideTable"),
    ("ScrubBrush", ""),
    ("Lettuce", "Bowl"),
    ("Cloth", "BathtubBasin"),
    ("BathtubBasin", ""),
    ("Candle", "Cabinet"),
    ("SoapBar", "Cabinet"),
    ("ButterKnife", "SideTable"),
    ("PotatoSliced*", "TVStand"),
    ("Egg", "Pan"),
    ("PepperShaker", "SideTable"),
    ("Statue", "Box"),
    ("Mug", "Cabinet"),
    ("TeddyBear", "CounterTop"),
    ("Pen", "Dresser"),
    ("ToiletPaper", "Dresser"),
    ("ShowerCurtain", ""),
    ("CreditCard", "Shelf"),
    ("ToiletPaper", "Cart"),
    ("Bottle", "SideTable"),
    ("Desktop", ""),
    ("Potato", "CoffeeTable"),
    ("WineBottle", "CoffeeTable"),
    ("Desk", ""),
    ("Dresser", ""),
    ("Fork", "SideTable"),
    ("Pan", "SinkBasin"),
    ("CreditCard", "DiningTable"),
    ("SaltShaker", "CounterTop"),
    ("Television", ""),
    ("EggCracked*", "SideTable"),
    ("TissueBox", "Drawer"),
    ("Watch", "Desk"),
    ("DishSponge", "Pan"),
    ("Spoon", "Bowl"),
    ("Book", "Ottoman"),
    ("PotatoSliced*", "Plate"),
    ("Cup", "Shelf"),
    ("KeyChain", "Dresser"),
    ("WateringCan", "CounterTop"),
    ("PotatoSliced*", "GarbageCan"),
    ("SoapBottle", "Cabinet"),
    ("PotatoSliced*", "Microwave"),
    ("Candle", "CounterTop"),
    ("SoapBar", "CounterTop"),
    ("Spatula", "Drawer"),
    ("SaltShaker", "SideTable"),
    ("Box", "Sofa"),
    ("BaseballBat", "CounterTop"),
    ("Curtains", ""),
    ("Fork", "SinkBasin"),
    ("LettuceSliced*", "TVStand"),
    ("EggCracked*", "SinkBasin"),
    ("CounterTop", ""),
}


RECEP_OBJS_IN = {
    "Toaster",
    "Microwave",
    "Safe",
    "Drawer",
    "CoffeeMachine",
    "Pan",
    "Pot",
    "Cup",
    "Cabinet",
    "Mug",
    "Box",
    "Fridge",
    "LaundryHamper",
    "Bathtub",
    "Bowl",
    "BathtubBasin",
    "SinkBasin",
    "GarbageCan",
}


OBJ_WASHING = {
    ("Bowl", "Faucet"),
    ("Pan", "Faucet"),
    ("Pot", "Faucet"),
    ("Cloth", "Faucet"),
    ("Cup", "Faucet"),
    ("Plate", "Faucet"),
    ("Mug", "Faucet"),
    ("Cloth", "ShowerHead"),
}
OBJ_FILLING_WATER = {
    ("Bottle", "Faucet"),
    ("Bowl", "Faucet"),
    ("Cup", "Faucet"),
    ("Kettle", "Faucet"),
    ("Mug", "Faucet"),
    ("WateringCan", "Faucet"),
}
OBJ_FILLING_COFFEE = {("Mug", "CoffeeMachine")}
OBJ_FILLING_WINE = {("Cup", "WineBottle")}
OBJ_EMPTYING = {
    ("Bottle", "SinkBasin"),
    ("Bowl", "SinkBasin"),
    ("Cup", "SinkBasin"),
    ("Kettle", "SinkBasin"),
    ("Mug", "SinkBasin"),
    ("WateringCan", "SinkBasin"),
}
FOR_STOVE = {"Pan", "Kettle", "Pot"}
OBJ_COOKING = {
    ("Bread", "Toaster"),
    ("Bread", "Pan", "StoveBurner"),
    ("Bread", "Pot", "StoveBurner"),
    ("Egg", "Pan", "StoveBurner"),
    ("Egg", "Bowl", "Microwave"),
    ("Egg", "Plate", "Microwave"),
    ("Potato", "Pan", "StoveBurner"),
    ("Potato", "Pot", "StoveBurner"),
    ("Potato", "Microwave"),
    ("Potato", "Microwave"),
}
OBJ_WITH_TEMPERATURE = {
    "Apple",
    "Bottle",
    "Bowl",
    "Bread",
    "Cup",
    "Egg",
    "Lettuce",
    "Mug",
    "Plate",
    "Potato",
    "Tomato",
    "WineBottle",
    "AppleSliced",
    "BreadSliced",
    "EggCracked",
    "LettuceSliced",
    "PotatoSliced",
    "TomatoSliced",
}
OBJ_HEATING = {
    ("Mug", "CoffeeMachine"),
    ("Kettle", "StoveBurner"),
    ("Pan", "StoveBurner"),
    ("Pot", "StoveBurner"),
} | {(x, "Microwave") for x in OBJ_WITH_TEMPERATURE}
OBJ_COOLING = {(x, "Fridge") for x in OBJ_WITH_TEMPERATURE}
FOR_SLICING = {"Apple", "Potato", "Tomato", "Lettuce", "Bread"}
OBJ_SLICING = {(x, "Knife") for x in FOR_SLICING} | {
    (x, "ButterKnife") for x in FOR_SLICING
}
